// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCdi76kMOjbenLhqaUaYjZIsyfHR1r-sQ',
    appId: '1:1033555722567:android:d2326a27350d23b0390c62',
    messagingSenderId: '1033555722567',
    projectId: 'libreriaupec-d084c',
    storageBucket: 'libreriaupec-d084c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnPMz4E_SBeVlsALNeUcqF4zUdtMYU0wQ',
    appId: '1:1033555722567:ios:8b4949179ab03724390c62',
    messagingSenderId: '1033555722567',
    projectId: 'libreriaupec-d084c',
    storageBucket: 'libreriaupec-d084c.appspot.com',
    iosClientId: '1033555722567-tiqv3npqsticdr02klu3ca2keaq1aoej.apps.googleusercontent.com',
    iosBundleId: 'com.example.upecLibraryBloc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnPMz4E_SBeVlsALNeUcqF4zUdtMYU0wQ',
    appId: '1:1033555722567:ios:8b4949179ab03724390c62',
    messagingSenderId: '1033555722567',
    projectId: 'libreriaupec-d084c',
    storageBucket: 'libreriaupec-d084c.appspot.com',
    iosClientId: '1033555722567-tiqv3npqsticdr02klu3ca2keaq1aoej.apps.googleusercontent.com',
    iosBundleId: 'com.example.upecLibraryBloc',
  );
}
